### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by Icermann** [ktechmidas/garlictipsbot#1]
Hi.

It looks like your code would be vulnerable to SQL injection attacks.
I believe the cursor.execute function can handle parameterized sql queries.

I.e. don't do
```
sql = "UPDATE withdraw SET confirmed=1 WHERE username='%s'" % username
cursor.execute(sql)
```

Instead do
```
sql = "UPDATE withdraw SET confirmed=1 WHERE username='%s'"
cursor.execute(sql, (username,))
```

Disclaimer: I'm not a Python programmer so I will not make a pull request. I have however worked with database systems in other languages.

Good job with the GRLC tip bot!

[Related](https://stackoverflow.com/questions/775296/python-mysql-parameterized-queries)

**Comment by ktechmidas** [comment]
Oh my... After a bit of searching, yes you're right, for some reason I thought it wasn't vulnerable to the same issues as the PHP mysql_connect (I remember dealing with that one years ago) and cursor.execute would do the preps automatically (At least that's what I thought I read...)

I've fixed the injection issues and pushed to master. That should fix it.
